#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "=== Analytics Hub Deploy ==="

# Step 1: Terraform init + apply
echo ""
echo "1. Running Terraform..."
cd "$PROJECT_ROOT/terraform"
terraform init
terraform apply -auto-approve

# Step 2: Get the API URL
API_URL=$(terraform output -raw api_url)
echo ""
echo "2. API Gateway URL: $API_URL"

# Step 3: Update config.js with the API URL
echo ""
echo "3. Updating js/config.js with API URL..."
cat > "$PROJECT_ROOT/js/config.js" << EOF
/**
 * Analytics Hub - Configuration
 * Auto-generated by deploy.sh
 */
const AppConfig = {
  API_BASE_URL: '${API_URL}'
};
EOF

echo ""
echo "=== Deploy Complete ==="
echo ""
echo "API URL: $API_URL"
echo "config.js has been updated."
echo ""
echo "Next steps:"
echo "  1. Test: curl $API_URL/api/divisions"
echo "  2. Push frontend to GitHub Pages: git add -A && git commit -m 'deploy' && git push"
